name: Build Main Binary

on:
  push:
    branches:
      - main

jobs:
  build-binary:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    uses: amtoaer/bili-sync/.github/workflows/build-binary.yaml@main
